<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (m, e, t, r, i, k, a) {
        m[i] = m[i] || function () {
            (m[i].a = m[i].a || []).push(arguments)
        };
        m[i].l = 1 * new Date();
        k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
    })
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(56734708, "init", {
        clickmap: true,
        trackLinks: true,
        accurateTrackBounce: true,
        webvisor: true
    });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/56734708" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<section id="section-fs-header" class="vertical-center" style="background-image: url(/img/bgr-01.jpg); min-height: 1008px;">
    <!--Header Captions + Buttons-->
    <div class="fs-header-captions">

        <!--Headings-->
        <h1 class="section-title-x-large pb-30">Фотосалон &quot;ПРИЗМА&quot;</h1>
        <h2 class="post-title pb-40">на Волгаре</h2>            

    </div>

    <!--Scroll Down Icon-->
    <div class="scroll-down-box">
        <a href="#section-page-header" class="page-scroll"><i class="xc icon-down-angle icon-float animated scroll-down-icon"></i></a>
    </div>

</section>

<section class="box-shadow-bottom"></section>

<section class="pricing-mp" id="section-page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!--Heading-->
                <h1>Услуги и цены
                    <small>Наши цены и наше качество приятно удивят Вас.</small>
                </h1>
            </div>
            <!--Breadcrumb-->
            <div class="col-md-4">
                <div class="breadcrumb">
                    <ul>
                        <li><a href="#section-fs-header">Главная</a></li>                 
                        <li>Прайс</li>
                    </ul>
                </div> 
            </div>
        </div><!--/.row-->    
    </div>
</section> 

<section class="box-shadow-bottom" id="photo-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-title text-center">ФОТОУСЛУГИ</h2>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">                
                <p class="intro-text text-center pb-50">
                    Мы используем фотобумагу и светостойкие чернила для фотопечати только высокого качества.<br />
                    Для того чтобы максимально ускорить печать фотографий присылайте Ваши файлы к нам на <a href="#section-page-header-contact">почту или в Viber</a>. 
                    Не забудьте указать в сообщении желаемый формат и количество копий.</p>
            </div>
        </div> <!-- /.row -->

        <div itemtype="http://schema.org/Product" itemscope>
            <meta itemprop="name" content="Распечатка фото">
            <div itemprop="offers" itemtype="http://schema.org/Offer" itemscope>
                <meta itemprop="price" content="7.00">                
                <meta itemprop="priceCurrency" content="RUB">
            </div>
            <div itemprop="offers" itemtype="http://schema.org/AggregateOffer" itemscope>
                <meta itemprop="lowPrice" content="7.00">
                <meta itemprop="highPrice" content="80.00">
                <meta itemprop="priceCurrency" content="RUB">
            </div>
            <meta itemprop="description" content="10х15-7 руб, 13х18-20 руб, 15х20-20руб, 21х30(А4)-40 руб, 30х42(А3)-80 руб." />
        </div>
        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Фотопечать 10х15</h3>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="7.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 7 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Суперглянец</li>
                        <li class="list-group-item">Глянец</li>
                        <li class="list-group-item">Более 100 листов - скидка 10%</li>                        
                    </ul>
                    <meta itemprop="description" content="Матовая, Суперглянец, Глянец. Более 100 листов - скидка 10%" />                    
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Фотопечать 13х18</h3>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="20.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 20 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>                        
                        <li class="list-group-item">Глянец</li>                        
                    </ul>
                    <meta itemprop="description" content="Матовая, Глянец" />
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Фотопечать 15х20</h3>                          
                    </div><!--/.panel-heading-->
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="20.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 20 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Глянец</li>                        
                    </ul>
                    <meta itemprop="description" content="Матовая, Глянец" />                    
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Фотопечать 21х30 (А4)</h3>
                    </div><!--/.panel-heading-->
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="40.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 40 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Глянец</li>                        
                    </ul>  
                    <meta itemprop="description" content="Матовая, Глянец" />                    
                </div>
            </div> 

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Фотопечать 30х42 (А3)</h3>
                    </div><!--/.panel-heading-->
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="80.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 80 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Глянец</li>                        
                    </ul>
                    <meta itemprop="description" content="Матовая, Глянец" />                    
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Фото на документы</h3>
                    </div><!--/.panel-heading-->
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="150.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 150 <sup class="coin">00</sup></span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Обработка, ретуширование, подстановка одежды/обмундирования.</li>                        
                    </ul>
                    <meta itemprop="description" content="Обработка, ретуширование, подстановка одежды/обмундирования." />
                </div>
            </div>

        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom" id="poligraph-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-title text-center">ПОЛИГРАФИЧЕСКИЕ УСЛУГИ</h2>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="intro-text text-center pb-50">Для того чтобы максимально ускорить печать документов присылайте Ваши файлы к нам на <a href="#section-page-header-contact">почту или в Viber</a>. Не забудьте указать в сообщении желаемый формат и количество копий.</p>
            </div>0
        </div> <!-- /.row -->

        <div itemtype="http://schema.org/Product" itemscope>
            <meta itemprop="name" content="Распечатка документов" />
            <div itemprop="offers" itemtype="http://schema.org/Offer" itemscope>
                <meta itemprop="price" content="5.00">                
                <meta itemprop="priceCurrency" content="RUB">
            </div>
            <div itemprop="offers" itemtype="http://schema.org/AggregateOffer" itemscope>
                <meta itemprop="lowPrice" content="3.00">
                <meta itemprop="highPrice" content="30.00">
                <meta itemprop="priceCurrency" content="RUB">
            </div>
            <meta itemprop="description" content="А4 черно-белая (до 20 страниц)-5 руб, А4 черно-белая (21-30 страниц)-4 руб, А4 черно-белая (более 31 страниц)-4 руб, А4 цветная-15 руб, А3 черно-белая-15 руб, А3 цветная-30 руб." />
        </div>

        <div itemtype="http://schema.org/Product" itemscope>
            <meta itemprop="name" content="Ксерокопия" />
            <div itemprop="offers" itemtype="http://schema.org/Offer" itemscope>
                <meta itemprop="price" content="5.00">
                <meta itemprop="priceCurrency" content="RUB">
            </div>
            <meta itemprop="description" content="А4 черно-белое-5 руб, А4 цветное-10 руб, А3 черно-белое-15 руб, А3 цветное-30 руб." />
        </div>

        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Копирование</h3>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="5.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div itemprop="offers" itemtype="http://schema.org/AggregateOffer" itemscope>
                        <meta itemprop="lowPrice" content="5.00">
                        <meta itemprop="highPrice" content="30.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 5 <sup class="coin">00</sup></span>
                        <span class="period">1 прогон</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">А4 черно-белое <strong>5 руб</strong></li>
                        <li class="list-group-item">А4 цветное <strong>10 руб</strong></li>                        
                        <li class="list-group-item">А3 черно-белое <strong>15 руб</strong></li>                        
                        <li class="list-group-item">А3 цветное <strong>30 руб</strong></li>                        
                    </ul>
                    <meta itemprop="description" content="А4 черно-белое-5 руб, А4 цветное-10 руб, А3 черно-белое-15 руб, А3 цветное-30 руб." />
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Печать документов</h3>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="5.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div itemprop="offers" itemtype="http://schema.org/AggregateOffer" itemscope>
                        <meta itemprop="lowPrice" content="3.00">
                        <meta itemprop="highPrice" content="30.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 5 <sup class="coin">00</sup></span>
                        <span class="period">1 страница</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">А4 черно-белая (более 31 страниц) <strong>3 руб</strong></li>
                        <li class="list-group-item">А4 черно-белая (21-30 страниц) <strong>4 руб</strong></li>
                        <li class="list-group-item">А4 черно-белая (до 20 страниц) <strong>5 руб</strong></li>
                        <li class="list-group-item">А4 цветная <strong>15 руб</strong></li>                        
                        <li class="list-group-item">А3 черно-белая <strong>15 руб</strong></li>                        
                        <li class="list-group-item">А3 цветная <strong>30 руб</strong></li>                        
                    </ul>
                    <meta itemprop="description" content="А4 черно-белая (до 20 страниц)-5 руб, А4 черно-белая (21-30 страниц)-4 руб, А4 черно-белая (более 31 страниц)-4 руб, А4 цветная-15 руб, А3 черно-белая-15 руб, А3 цветная-30 руб." />
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Ламинирование</h3>                          
                    </div><!--/.panel-heading-->
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="30.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div itemprop="offers" itemtype="http://schema.org/AggregateOffer" itemscope>
                        <meta itemprop="lowPrice" content="30.00">
                        <meta itemprop="highPrice" content="60.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 30 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">А6 <strong>30 руб</strong></li>
                        <li class="list-group-item">А5 <strong>40 руб</strong></li>
                        <li class="list-group-item">А4 <strong>50 руб</strong></li>
                        <li class="list-group-item">А3 <strong>60 руб</strong></li>
                    </ul>
                    <meta itemprop="description" content="A6-30 руб, А5-40 руб, А4-50 руб, А3-60 руб." />
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Пакет документов для выпуска карты водителя СКЗИ</h3>                          
                    </div><!--/.panel-heading-->
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="300.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 30 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Копия паспорта</li>
                        <li class="list-group-item">Копия ИНН</li>
                        <li class="list-group-item">Копия водительского удостоверения</li>
                        <li class="list-group-item">Копия СНИЛС</li>
                        <li class="list-group-item">Фото</li>
                        <li class="list-group-item">Заявление по утвежденной форме</li>                        
                    </ul>
                    <meta itemprop="description" content="Копия паспорта, копия ИНН, копия водительского удостоверения, копия СНИЛС, фото, заявление по утвежденной форме" />
                </div>
            </div>
        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom" id="digital-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-title text-center">ЦИФРОВЫЕ УСЛУГИ</h2>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="intro-text text-center pb-50">Обращаем Ваше внимание на то, что оцифровка видео и фото может занять несколько дней в зависимости от размера видео и количества фото материала.<br />
                    Видео конвертируется в формат H.256 (MPEG4). Если Вы желаете получить видео в другом формате информируйте об этом при приемке заказа.</p>
            </div>
        </div> <!-- /.row -->

        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Сканирование</h3>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="5.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 5 <sup class="coin">00</sup></span>
                        <span class="period">1 прогон</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">А4 (JPEG, PDF) <strong>₽5</strong></li>                        
                        <li class="list-group-item">А3 (JPEG, PDF) <strong>₽15</strong></li>                                                
                    </ul>  
                    <meta itemprop="description" content="Сканируем документы, фото, изображения в форматы PDF и JPG." />
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Оцифровка видео</h3>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="5.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 5 <sup class="coin">00</sup></span>
                        <span class="period">1 минута</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>VHS, Compact VHS</strong></li>                        
                        <li class="list-group-item"><strong>miniDV</strong></li>
                        <li class="list-group-item"><strong>Hi8</strong></li>
                        <li class="list-group-item"><strong>Оцифровываем в формат HD</strong></li>
                    </ul>
                    <meta itemprop="description" content="Цена указана за 1 минуту видео. Оцифровываем с любых носителей (VHS, Compact VHS, miniDV, Hi8). Оцифровываем в формат HD" />
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Оцифровка ФОТО</h3>                            
                    </div><!--/.panel-heading-->
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="5.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 5 <sup class="coin">00</sup></span>
                        <span class="period">1 кадр</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Принимаем пленку 35мм</strong></li>                        
                    </ul>  
                    <meta itemprop="description" content="Цена указана за 1 кадр. Производим оцифровку фото в формат JPEG." />
                </div>
            </div>
        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom" id="site-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-title text-center">РАЗРАБОТКА САЙТОВ</h2>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="intro-text text-center pb-50">&nbsp;</p>
            </div>
        </div> <!-- /.row -->        

        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Сайт визитка</h3>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="25 000.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <br /> <sup>₽</sup> 25 000</span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Регистрация домена</strong></li>                        
                        <li class="list-group-item"><strong>Организация хостинга</strong></li>                                                
                        <li class="list-group-item"><strong>Продвижение сайта (SEO)</strong></li>                                                
                    </ul>
                    <meta itemprop="description" content="Включено: регистрация домена, организация хостинга, продвижение сайта (SEO)" />
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Сайт визитка адаптивный</h3>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="35 000.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <br /> <sup>₽</sup> 35 000</span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Идеально подходит как для настольных так и для мобильный устройств</strong></li>                        
                        <li class="list-group-item"><strong>Регистрация домена</strong></li>                        
                        <li class="list-group-item"><strong>Организация хостинга</strong></li>                                                
                        <li class="list-group-item"><strong>Продвижение сайта (SEO)</strong></li>                                                
                    </ul>
                    <meta itemprop="description" content="Включено: регистрация домена, организация хостинга, продвижение сайта (SEO)" />
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Сайт корпоративный</h3>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="50 000.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <br /> <sup>₽</sup> 50 000</span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Адаптивная верстка</strong></li>                        
                        <li class="list-group-item"><strong>Регистрация домена</strong></li>                        
                        <li class="list-group-item"><strong>Организация хостинга</strong></li>                                                
                        <li class="list-group-item"><strong>Продвижение сайта (SEO)</strong></li>                                                
                    </ul>
                    <meta itemprop="description" content="Включено: адаптивная верстка, регистрация домена, организация хостинга, продвижение сайта (SEO)" />
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center" itemtype="http://schema.org/Product" itemscope>
                    <div class="panel-heading">
                        <h3 class="panel-title" itemprop="name">Интернет магазин</h3>
                    </div>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="price" content="50 000.00">
                        <meta itemprop="priceCurrency" content="RUB">
                    </div>
                    <div class="panel-body">
                        <span class="price">от <br /> <sup>₽</sup> 50 000</span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">                        
                        <li class="list-group-item"><strong>Адаптивная верстка</strong></li>                        
                        <li class="list-group-item"><strong>Регистрация домена</strong></li>                        
                        <li class="list-group-item"><strong>Организация хостинга</strong></li>                                                
                        <li class="list-group-item"><strong>Продвижение сайта (SEO)</strong></li>                                                
                    </ul>
                    <meta itemprop="description" content="Включено: адаптивная верстка, регистрация домена, организация хостинга, продвижение сайта (SEO)" />
                </div>
            </div>

        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom"></section>

<section id="section-page-header-contact" class="contact-mp-2">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!--Heading-->
                <h1>Наши контакты
                    <small>&nbsp;</small></h1>
            </div>
            <div class="col-md-4">
                <!--Breadcrumb-->
                <div class="breadcrumb-alt">
                    <ul>
                        <li><a href="#section-fs-header">Главная</a></li>                 
                        <li>Контакты</li>
                    </ul>
                </div> 
            </div>
        </div><!--/.row-->    
    </div>
</section> 

<div style="background-color:#282828">
    <!-- Map Buttons -->
    <div class="container">
        <div id="map-btn1-contain" style="background:#282828">
            <a id="map-btn1" class="gmap-btn close-map-button btn-show" href="#map">Карта <i class="fa fa-angle-down"></i></a>
        </div>
        <a id="map-btn2" class="gmap-btn active close-map-button btn-hide" href="#map">Скрыть карту <i class="fa fa-angle-up"></i></a>
    </div>

    <!-- Google Maps -->
    <section id="map" class="close-map">
        <div id="google-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2392.417706239952!2d50.073908815831295!3d53.15654417993975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1bd9a0038d9708e!2z0KTQvtGC0L7RgdCw0LvQvtC9INCf0KDQmNCX0JzQkA!5e0!3m2!1sru!2sru!4v1538251332567" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>        
        </div>
    </section>
</div>
<!-- /.Google Maps End -->


<!-- Contact Section -->
<section class="page-section-top-alt-np mt-25 pb-155 pb-md-105 pb-sm-85" id="contact-mp">  
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-6 contact-details text-left">
                <h3 class="dark-grey"></h3>
                <ul class="pt-20">
                    <li><strong>ул. Казачья, дом 34</strong></li>           
                    <li>мкрн Волгарь</li>
                    <li>Самара</li>
                </ul>
                <ul class="pt-10">
                    <li><i class="fa fa-phone"></i> +7(937)201-95-71, +7(937)983-72-78</li>           
                    <li><img src="/img/viber.png" style="width: 20px; display: inline; margin-left: -3px;"></i> +7(937)201-95-71</li>           
                    <li><i class="fa fa-envelope-o"></i>golovinanb@mail.ru</li>
                    <li><i class="fa fa-clock-o"></i>понедельник-пятница: 10:00-19:00</li>
                    <li><i class="fa fa-clock-o"></i>суббота: 11:00-15:00</li>
                </ul>
            </div>
            <!--Contact Form Start--> 
            <div class="col-sm-6 col-lg-6">

            </div>    
        </div><!--/.row End-->
    </div>
</section>

<footer>
    <section id="footer">
        <div class="container">  
            <div class="row">
                <!-- CopyRight Text -->
                <div class="col-md-6 col-sm-6">
                    <div class="copy-footer">
                        <p>Разработчик сайта: <a href="http://aleksandrgolovin.ru">Александр Головин</a></div>
                </div>
                <div class="col-md-6 col-sm-6" style="display: none;"> 
                    <div class="social text-center">
                        <ul> 
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>  
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul> 
                    </div>
                </div>                
            </div>
        </div>
    </section>

</footer>