<?=
$this->headTitle('Фотопечать, фото на документы в Самаре.')->setSeparator(' - ')->setAutoEscape(false);
$this->headMeta()
        ->appendName('description', 'Фотосалон Призма на Волгаре. Фотопечать различных форматов, срочное фото на любые документы, печать и ламинирование документов в Самаре, Куйбышевский район.')
        ->appendName('keywords', 'где сделать фото на документ,где сделать фото на паспорт,где сделать фото на загран,где сфотографироваться,где фотопечать,где печать фото,где сделать ксерокопию,где ламинировать документ,где распечатать');
?>

<section id="section-fs-header" class="vertical-center" style="background-image: url(/img/bgr-01-md.jpg); min-height: 1008px;">
    <!--Header Captions + Buttons-->
    <div class="fs-header-captions">

        <!--Headings-->
        <h1 class="section-title-x-large pb-30">Фотосалон &quot;ПРИЗМА&quot;</h1>
        <h2 class="post-title pb-40">на Волгаре</h2>            

    </div>

    <!--Scroll Down Icon-->
    <div class="scroll-down-box">
        <a href="#section-page-header" class="page-scroll"><i class="xc icon-down-angle icon-float animated scroll-down-icon"></i></a>
    </div>

</section>

<section class="box-shadow-bottom"></section>

<section class="pricing-mp" id="section-page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!--Heading-->
                <h2>Наши услуги.
                    <small>Низкие цены. Высокое качество.</small>
                </h2>
            </div>
            <!--Breadcrumb-->
            <div class="col-md-4">
                <div class="breadcrumb">
                    <ul>
                        <li><a href="#section-fs-header">Главная</a></li>                 
                        <li>Прайс</li>
                    </ul>
                </div> 
            </div>
        </div><!--/.row-->    
    </div>
</section> 

<section class="box-shadow-bottom" id="photo-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h3 class="section-title text-center">ФОТОУСЛУГИ</h3>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">                
                <p class="intro-text text-center pb-50">
                    Мы используем фотобумагу и светостойкие чернила для фотопечати только высокого качества.<br />
                    Для того чтобы максимально ускорить печать фотографий присылайте Ваши файлы к нам на <a href="#section-page-header-contact">почту или в Viber</a>. 
                    Не забудьте указать в сообщении желаемый формат, тип бумаги и количество копий.</p>
            </div>
        </div> <!-- /.row -->
        
        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Распечатка фото 10х15</h4>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 15 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Суперглянец</li>
                        <li class="list-group-item">Глянец</li>
                        <!-- <li class="list-group-item discont">Более 100 листов - скидка 10%</li>                        -->
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Распечатка фото 13х18</h4>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 35 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>                        
                        <li class="list-group-item">Глянец</li>                        
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Распечатка фото 15х20</h4>                          
                    </div><!--/.panel-heading-->
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 35 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Глянец</li>                        
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Распечатка фото 21х30 (А4)</h4>
                    </div><!--/.panel-heading-->
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 70 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Глянец</li>                        
                    </ul>  
                </div>
            </div> 

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Распечатка фото 30х42 (А3)</h4>
                    </div><!--/.panel-heading-->
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 200 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Матовая</li>
                        <li class="list-group-item">Глянец</li>                        
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Фото на документы</h4>
                    </div><!--/.panel-heading-->
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 250 <sup class="coin">00</sup></span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Электронное фото для Госуслуг <br/><strong>+₽50</strong></li>                        
                        <li class="list-group-item">Подстановка одежды (обмундирования)<br/><strong>+₽50</strong></li>                                                
                        <li class="list-group-item">Печать дополнительного листа<br /><strong>+₽150</strong></li>                        
                    </ul>
                </div>
            </div>

        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom" id="poligraph-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h3 class="section-title text-center">ПОЛИГРАФИЧЕСКИЕ УСЛУГИ</h3>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="intro-text text-center pb-50">Для того чтобы максимально ускорить печать документов присылайте Ваши файлы к нам на <a href="#section-page-header-contact">почту или в Viber</a>. Не забудьте указать в сообщении желаемый формат и количество копий.</p>
            </div>0
        </div> <!-- /.row -->


        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Ксерокопия</h4>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 10 <sup class="coin">00</sup></span>
                        <span class="period">1 прогон</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">А4 черно-белое <strong>₽10</strong></li>
                        <li class="list-group-item">А4 цветное <strong>₽15</strong></li>                        
                        <li class="list-group-item">А3 черно-белое <strong>₽30</strong></li>                        
                        <li class="list-group-item">А3 цветное <strong>₽60</strong></li>                        
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Распечатка документов</h4>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 10 <sup class="coin">00</sup></span>
                        <span class="period">1 страница</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">А4 черно-белая <strong>₽10</strong></li>
                        <!-- <li class="list-group-item discont">А4 черно-белая (50 страниц и более) <br/><strong>₽5</strong></li> -->
                        <!-- <li class="list-group-item discont">А4 черно-белая (более 100 страниц) <br/><strong>₽4</strong></li> -->
                        <li class="list-group-item">А4 цветная <strong>₽15</strong></li>                        
                        <li class="list-group-item">А4 цветная (улучшенная цветопередача)<br/><strong>₽25</strong></li>                        
                        <li class="list-group-item">А3 черно-белая <strong>₽30</strong></li>                        
                        <li class="list-group-item">А3 цветная <strong>₽60</strong></li>                        
                        <!-- <li class="list-group-item">А4 черно-белая двусторонняя <br/><strong>₽5/сторона</strong></li>                        
                        <li class="list-group-item">А4 цветная двусторонняя <br/><strong>₽8/сторона</strong></li>                        
                        <li class="list-group-item">А3 черно-белая двусторонняя <br/><strong>₽20/сторона</strong></li>                        
                        <li class="list-group-item">А4 цветная двусторонняя <br/><strong>₽50/сторона</strong></li> -->
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Ламинирование</h4>                          
                    </div><!--/.panel-heading-->
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 70 <sup class="coin">00</sup></span>
                        <span class="period">1 лист</span>
                    </div>
                    <ul class="list-group">                        
                        <li class="list-group-item">А4 <strong>₽70</strong></li>
                        <li class="list-group-item">А3 <strong>₽100</strong></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Пакет документов для выпуска карты тахографа</h4>                          
                    </div><!--/.panel-heading-->
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 400 <sup class="coin">00</sup></span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Необходимые документы</strong></li>                        
                        <li class="list-group-item">Паспорт</li>
                        <li class="list-group-item">ИНН</li>
                        <li class="list-group-item">Водительское удостоверение</li>
                        <li class="list-group-item">СНИЛС</li>
                        <li class="list-group-item">Карта тахографа (если имеется)</li>                        
                    </ul>
                </div>
            </div>
        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom" id="digital-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h3 class="section-title text-center">ЦИФРОВЫЕ УСЛУГИ</h3>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="intro-text text-center pb-50">Обращаем Ваше внимание на то, что оцифровка может занять несколько дней в зависимости от размера видео и количества фото материала.<br />
                    Видео конвертируется в формат H.256 (MPEG4). Если Вы желаете получить видео в другом формате информируйте об этом при приемке заказа.</p>
            </div>
        </div> <!-- /.row -->

        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Сканирование</h4>
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 15 <sup class="coin">00</sup></span>
                        <span class="period">1 прогон</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Документ А4 (PDF) <strong>₽15</strong></li>                        
                        <li class="list-group-item">Документ А3 (PDF) <strong>₽50</strong></li>                                                
                        <li class="list-group-item">Фото/Изображение А4 (JPEG) <strong>₽50</strong></li>                        
                        <li class="list-group-item">Фото/Изображение А3 (JPEG) <strong>₽150</strong></li>                                                
                    </ul>  
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <a href="/Digivideo"><h4 class="panel-title">Оцифровка видеокассет</h4></a>
                        <!--Best Offer Label-->
                        <div class="ribbon"></div>
                        <div class="ribbon-inner"></div> 
                        <div class="best-offer-thumb">Хит услуг</div>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 15 <sup class="coin">00</sup></span>
                        <span class="period">1 минута</span>
                    </div>
                    <!--<ul class="list-group">
                        <li class="list-group-item discont"><strong>При длительности<br> от 45 до 90 минут - 8,5₽/минута</strong></li>                        
                        <li class="list-group-item discont"><strong>При длительности<br> от 90 минут - 7₽/минута</strong></li>                        
                        <li class="list-group-item"><strong>Принимаем кассеты<br>VHS, Compact VHS, miniDV, Hi8</strong></li>                                                
                        <li class="list-group-item"><strong>Оцифровываем в формат HD<br/>720х576</strong></li>
                    </ul> -->
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Оцифровка фотопленки и слайдов</h4>                            
                    </div><!--/.panel-heading-->
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 25 <sup class="coin">00</sup></span>
                        <span class="period">1 кадр</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Принимаем пленку 35мм</strong></li>                        
                    </ul>  
                </div>
            </div>
            
            <!--<div class="col-lg-4 col-md-6 col-sm-6">
                <div class="panel panel-alter-odd text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Реставрация фотографий</h4>                            
                    </div>
                    <div class="panel-body">
                        <span class="price">от <sup>₽</sup> 400 <sup class="coin">00</sup></span>                        
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Удаление трещин, пятен: от ₽400 </strong></li>                        
                        <li class="list-group-item"><strong>Восстановление утерянных участков: от ₽800 </strong></li>                        
                        <li class="list-group-item"><strong>Цветокоррекция: от ₽50 </strong></li>                        
                        <li class="list-group-item"><strong>Сильные повреждения, фотомонтаж: от ₽1200 </strong></li>                        
                    </ul>  
                </div>
            </div>-->
        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom" id="site-pricing"></section>

<section class="page-section-top-alt-np pb-135 pb-md-85 pb-sm-65 pricing">
    <div class="container">

        <!-- Section Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h3 class="section-title text-center">ПРОЧИЕ УСЛУГИ</h3>
            </div>
        </div> <!-- /.row -->

        <!-- Section Description -->
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="intro-text text-center pb-50">&nbsp;</p>
            </div>
        </div> <!-- /.row -->        

        <!-- Panels -->
        <div class="row pb-5">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Отпрвка почты e-mail</h4>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 50 <sup class="coin">00</sup></span>
                        <span class="period"></span>
                    </div>                    
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Запись DVD диска + диск</h4>
                    </div>
                    <div class="panel-body">
                        <span class="price"> <sup>₽</sup> 200 <sup class="coin">00</sup></span>
                        <span class="period"></span>
                    </div>                   
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="panel panel-alter text-center">
                    <div class="panel-heading">
                        <h4 class="panel-title">Печать бланков</h4>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>₽</sup> 20 <sup class="coin">00</sup></span>
                        <span class="period"></span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Договора купли/продажи</strong></li>                        
                        <li class="list-group-item"><strong>Доверенности</strong></li>                        
                        <li class="list-group-item"><strong>прочее</strong></li>                                                                        
                    </ul>
                </div>
            </div>            

        </div><!-- /.row -->     
    </div><!-- /.container -->
</section>

<section class="box-shadow-bottom" id="contacts"></section>

<section id="section-page-header-contact" class="contact-mp-2">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!--Heading-->
                <h2>Наши контакты
                    <small>&nbsp;</small></h2>
            </div>
            <div class="col-md-4">
                <!--Breadcrumb-->
                <div class="breadcrumb-alt">
                    <ul>
                        <li><a href="#section-fs-header">Главная</a></li>                 
                        <li>Контакты</li>
                    </ul>
                </div> 
            </div>
        </div><!--/.row-->    
    </div>
</section> 

<div style="background-color:#282828">
    <!-- Map Buttons -->
    <div class="container">
        <div id="map-btn1-contain" style="background:#282828">
            <a id="map-btn1" class="gmap-btn close-map-button btn-show" href="#map">Карта <i class="fa fa-angle-down"></i></a>
        </div>
        <a id="map-btn2" class="gmap-btn active close-map-button btn-hide" href="#map">Скрыть карту <i class="fa fa-angle-up"></i></a>
    </div>

    <!-- Google Maps -->
    <section id="map" class="close-map">
        <div id="google-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2392.417706239952!2d50.073908815831295!3d53.15654417993975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1bd9a0038d9708e!2z0KTQvtGC0L7RgdCw0LvQvtC9INCf0KDQmNCX0JzQkA!5e0!3m2!1sru!2sru!4v1538251332567" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>        
        </div>
    </section>
</div>
<!-- /.Google Maps End -->


<!-- Contact Section -->
<section class="page-section-top-alt-np mt-25 pb-155 pb-md-105 pb-sm-85" id="contact-mp">  
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-6 contact-details text-left">                
                <ul class="pt-20">
                    <li><strong>ул. Казачья, дом 34</strong></li>           
                    <li>мкрн Волгарь</li>
                    <li>Самара</li>
                </ul>
                <ul class="pt-10">
                    <li><i class="fa fa-phone"></i> +7(917)015-06-65, +7(937)201-95-71</li>           
                    <li><img src="/img/telegram.jpg" style="width: 20px; display: inline; margin-left: -3px;"></i> <a href="https://t.me/+79170150665">+7(917)015-06-65</a></li>           
                    <li><img src="/img/whatsapp.jpg" style="width: 20px; display: inline; margin-left: -3px;"></i> +7(917)015-06-65</li>           
                    <li><i class="fa fa-envelope-o"></i>golovinanb@mail.ru</li>
                    <li><i class="fa fa-clock-o"></i>понедельник-пятница: 09:00-19:00</li>
                    <li><i class="fa fa-clock-o"></i>суббота-воскресенье: выходной</li>
                    <li><hr></li>
                    <li><strong>Специалист по оцифровке</strong></li>
                    <li><i class="fa fa-phone"></i> +7(996)725-70-77</li>           
                    <li><img src="/img/telegram.jpg" style="width: 20px; display: inline; margin-left: -3px;"></i> <a href="https://t.me/GolovinSasha">@GolovinSasha</a></li>           
                </ul>
            </div>            
            
            <!--Contact Form Start--> 
            <div class="col-sm-6 col-lg-6">

            </div>    
        </div><!--/.row End-->
    </div>
</section>
